### ISSUE TITLE
channel stream freezes

### ISSUE THREAD

**Issue by RacerXnyc** [Soma-FM-Kodi-Add-On/plugin.audio.somafm#12]
Hey all, 

Hope this is the right place to note this, but since installing the app has started to act up.  The first 2,3 times I loaded a radio stream it worked fine.  But now, a stream will freeze basically the second it starts to play.  This happens about 80 percent of the time.  So 1 out of 5 times music will play, as expected.  But the other 4/5 as soon as a channel is selected and the play window opens sounds starts for... maybe 1/3 of a second and then then screen freezes.  You can't back out of it, you have to exit to home, kill Kodi and restart.

Seems to happen on any channel
Restarted the device doesn't seem to help

Device:  Nvidia Shield (2015)
OS: AndroidTV   (Shield Experience)
Android Version: 9
Shield Android TV SW Version:  8.2.3 (32.6.518.0)

Kodi v.:  19.3
SomaFM addon Version:  2.0.1

I'm not a coder but if you need anything else I'll help if I can.  I've been lauded as a good tester, lol...

**Comment by evinr** [comment]
Hey @RacerXnyc! 

Thanks for reporting this issue! Could I trouble you for the logs? 

Here is a link to help with finding the logs: https://kodi.wiki/view/Log_file/Easy

Also do you mind installing a the latest version from here as a zip, as it has better logging in place to help diagnose issues like this.

**Comment by RacerXnyc** [comment]
Ok, so here's what I did:

1- updated to current version (My files were from November, I noticed).  So I d/l'd the zip and copied it over to my kodi addon folder, replacing the folder with November files.

2- Ran SomaFM - First channel (Christmas Lounge) played successfully.  Stopped it and ran another (Secret Agent).  That channel froze.  Quit and restarted Kodi

3- Tried again - Same result, first channel (Christmas Lounge) ok, second channel (Secret Agent) froze.  Quit and restart.

4- Tried again- First channel (Deep Space Lounge) froze.  Quit and restart.

5- Ran the log.

6- Just to check something, I played Christmas Lounge, played successfully.  I stopped playback and then played Christmas Lounge again.  And it froze.  So it's not particular channels.  I mean, it wouldn't be, but just to be sure.


Here's the log file-

https://paste.kodi.tv/favovopubo


Lemme know if you need anything else!

**Comment by evinr** [comment]
Thanks! I am not able to see much from the log you posted. Can you enable debugging under Settings -> Logging, then trigger the issue, then extract the logs? Using ctrl + f to locate "somafm" should yield more than one result. 

Also, when you say you stopped the playing, is there a specific pause or stop button that is triggering the stop? I am not able to pause/stop any of the channels, just able to select a new one which starts playing without any issues. 

I tried to reproduce locally using the Android emulator that comes with Android Studio, but due to the different chipset architectures was not able to get Kodi installed for an Android TV device. ☹️

**Comment by RacerXnyc** [comment]
My pleasure-

Ok, so with debugging, I ran it twice:

Start kodi
(Turn on debugging)
Start SomaFM
Pick a channel (groove salad)
Play - freeze
Go to Android home screen
Force quit Kodi (task switcher- kill kodi)
Start Kodi
Start Soma FM
Pick a channel (I forgot what I picked)
Play - freeze
Android home - force quit
Start kodi 
Run Kodi log uploader

paste.kodi.tv/yesifasunu


What happens is- SomaFM starts normally.  I choose a channel and it starts to play:  The screen changes to a dj backdrop with channel information at the bottom.  It looks like there's a visualization that's about to start.  Then music starts to play but literally half a second in everything freezes.  You hear the first note or two of music and then the freeze.  Nothing external triggers this, it seems to be all within the app.  No buttons presses, etc.  Kodi becomes completely unresponsive and the only way out is to force quit it.

Here, I made a video:  https://youtu.be/xsU_aEcnAAg  

(The background noise is my heat coming on)

**Comment by evinr** [comment]
I am not seeing somafm launching in the logs. It looks something like this, "somafm/default.py): script successfully run" and just looking at "script successfully run" that it is mostly just startup scripts that are being logged.

I think that if you could to SSH into the machine and read the log after Soma FM crashes it will expose more than what the Kodi log uploader is providing. Not sure if you have experience with this, but this will need to be installed on the Nvidia Sheild: https://play.google.com/store/apps/details?id=com.arachnoid.sshelper and then you can use Putty (https://www.putty.org/) on Windows to connect. The log should be somewhere around here on Android: {storage}/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log

**Comment by RacerXnyc** [comment]
I wondered about that.  I guess Kodi cleans the log on every reboot.  I don't know ssh, actually, but- the Shield's drives are open on my network so I can just go into them from my pc and copy the .log file out.  That should be the same thing you're asking for?

This time:

Ran SomaFM
Ran a channel (Fluid) - plays correctly
Stopped playback and played the same channel again - freezes
From PC access <the xbmc/kodi/data/temp> folder and copy out the logs.

I checked it and it looks like it shows Soma as running.  But I'm not very familiar with log reading at all.
It's a pastebin, lemme know if you want a different format.  I also just share the file somewhere-

<My pastebin page seems to have been deleted.  Gimme a minute to re up it somewhere else>

Ok, this should work:

https://paste.kodi.tv/ucowicaruj.kodi

**Comment by evinr** [comment]
I think the issue is with the AudioDecoder, specifically the CDVDAudioCodecAndroidMediaCodec. I am not a pro at this, but the symptom only appearing the Shield which has the Tegra chip and Android 9 for the OS leads me to believe it is the decodering/codecs on that OS's chip-level instructions. 

Is that the only Android TV box you have available? I was thinking about getting a cheap Android TV box that runs Android 9 to try and determine if it is the hardware or that version of Android. 

**2021-12-28 16:43:54.516 T:11255   DEBUG <general>: CDVDDemuxFFmpeg::AddStream ID: 0
2021-12-28 16:43:54.517 T:11255   DEBUG <general>: CDVDAudioCodecAndroidMediaCodec::Open codec(86017), profile(-99), tag(0), extrasize(0)
2021-12-28 16:43:54.517 T:11255    INFO <general>: CDVDAudioCodecAndroidMediaCodec::Open() Use default handling for non encrypted stream
2021-12-28 16:43:54.517 T:11255    INFO <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder mp3float
2021-12-28 16:43:54.631 T:11255    INFO <general>: AudioDecoder: File is queued
2021-12-28 16:43:54.633 T:11255   DEBUG <general>: AudioDecoder::GetReplayGain - Final Replaygain applied: 1.000000, Track/Album Gain 89.000000, Peak 1.000000**
2021-12-28 16:43:54.640 T:11192   DEBUG <general>: CActiveAE::ClearDiscardedBuffers - buffer pool deleted
2021-12-28 16:43:54.648 T:11255    INFO <general>: PAPlayer::PrepareStream - Ready
2021-12-28 16:43:54.649 T:11295   DEBUG <general>: OnAVStarted: CApplication::OnAVStarted
2021-12-28 16:43:54.650 T:11192   DEBUG <general>: CActiveAE::ClearDiscardedBuffers - buffer pool deleted
2021-12-28 16:43:54.684 T:11172   DEBUG <general>: ------ Window Deinit (DialogBusy.xml) ------
2021-12-28 16:43:54.684 T:11172   DEBUG <general>: Updating visualization albumart: https://api.somafm.com/logos/512/fluid512.jpg
2021-12-28 16:43:59.825 T:11244   DEBUG <CAddonSettings[script.logviewer]>: trying to load setting definitions from old format...

2021-12-28 16:44:08.663 T:11150   DEBUG <general>: CXBMCApp::onReceive - Got intent. Action: android.intent.action.MEDIA_BUTTON
2021-12-28 16:44:08.667 T:11150    INFO <general>: Got MEDIA_BUTTON intent: 86, up:false
2021-12-28 16:44:08.693 T:11172   DEBUG <general>: Keyboard: scancode: 0x56, sym: 0x178, unicode: 0x0000, modifier: 0x0
2021-12-28 16:44:08.694 T:11172   DEBUG <general>: HandleKey: stop (0xf0bc) pressed, action is Stop

2021-12-28 16:44:08.789 T:11230   DEBUG <general>: DoWork - Saving file state for audio item plugin://plugin.audio.somafm/fluid
2021-12-28 16:44:08.792 T:11192   DEBUG <general>: CActiveAE::DiscardStream - audio stream deleted
2021-12-28 16:44:08.792 T:11192   DEBUG <general>: CActiveAE::ClearDiscardedBuffers - buffer pool deleted
2021-12-28 16:44:08.793 T:11230   DEBUG <general>: Skipped 2 duplicate messages..
2021-12-28 16:44:08.793 T:11230   DEBUG <general>: DoWork - Marking audio item plugin://plugin.audio.somafm/fluid as listened

**Comment by evinr** [comment]
@RacerXnyc Do you mind changing your settings to select aac first instead of mp3? And also selecting slow as the first options for quality? Then retesting and posting the log if it does not work?

**Comment by RacerXnyc** [comment]
So I changed the settings and a channel froze under 'aac' (only), and on 'mp3' (only).  With the default quality and with quality set to:  Low, medium, high.

So no dice.

I do have a SonyTV with AndroidTV 9 on it.  I can test with that.  But I don't have network access to the system drive, so it's more complex to load SomaFM, I would have to figure out SSH to get a log, etc.  Give me a day or so and I'll play with it.  Maybe I'll put this out on Reddit also, see if any of the other Shield users are interested in testing their setups as well.

**Comment by RacerXnyc** [comment]
Ok, just observed some interesting things.  Turns out I had SomaFM on my other AndroidTV device already (the Sony TV).

The old SomaFM plays correctly with no issues on the SonyTV (w/AndroidTV)
The new SomaFM files play correctly with no issues also.  4 channels, play for a bit, stopped, selected new channel.

I did notice something, though-

On the Shield- when I play a channel, there is a visualization that plays over the SomaFM backdrop.  It's squiggly, radio wave frequency lines.  In the youtube video I uploaded, you can probably just begin to see the visualization start to trace.

The SonyTV has no such visualization over the screen when playing.

Back on the Shield, the visualization setting was turned on, and so I turned it off.  And to be safe, I turned off all the screensaver settings as well (which overlap with the visualization settings).   But with all of those settings turned off, the visualization still began to play when I started a SomaFM channel stream.

(Edit to add- those times when the channels did play successfully, the visualization also played successfully)

I'll investigate where that might be coming from.  I don't know if that's likely to potentially be the problem or not. 

The TV is a Sony Bravia 49x950H with Android 9

That's it for now...

![image](https://user-images.githubusercontent.com/27899684/147788820-2cd8b2df-3d5b-4bff-afe4-c80175aabb43.png)

**Comment by RacerXnyc** [comment]
Hey,

I just realized you asked for logs after trying aac / slow quality.  So I ran it again:

Changed settings to aac only, slow/(medium/high?  I forget)
Cleared the cache through the settings.
Played 1 channel (christmas lounge)
  - 1 st time looked like it was going to freeze, or- froze for a split second, but then played correctly
  - 2nd & 3rd time - played correctly
  - 4 time, switched channels to Covers - playback froze.

Here's the log:  

https://paste.kodi.tv/vapeheyage.kodi

I don't recall ever playing a channel three times without a freeze.  

And oh- here's a video showing the visualization playing.  I for the life of me can't figure out how to turn this off.   Again- the SomaFM on my Sony tv (AndroidTV) does not have this.

https://youtu.be/Bqx4XRf6Dus

**Comment by RacerXnyc** [comment]
Ok, so I figured it out.  It was in fact the visualization that was the conflict.

The visualization add-on FishBMC, from the official Kodi repository, conflicts with SomaFM.  Removing this add-on fixed SomaFM completely.  

A couple things:

I played around a bit with the settings, reducing the intensity, cpu load as well as the stream quality and codec.  I didn't try every combination, but generally, nothing seemed to have any effect, although it did seem to increase the number of times that SomaFM would work on first run.  As opposed to crashing the first time you run it, which it often does.

Interestingly, I had all visualizations disabled.  So this add-on will interfere with SomaFM if it's installed but disabled.  It will have to be completely uninstalled to fix any issues.

Since I don't really need or use it, for myself I'm happy to remove FishBMC and for me the issue is resolved.  I may drop a note over to the FishBMC people to let them know.  Of course I don't know where the actual conflict between addons is.  

It's interesting that there was no place to turn on FishBMC.  Somehow it started running itself.  It was installed and enabled, but it turned itself on whenever SomaFM ran, somehow.

I guess that's it.  If you need anything else, let me know!

-Rx

**Comment by RacerXnyc** [comment]
Issue's solved, so I'm closing it!
